### ISSUE TITLE
inverse uses dynamic memory

### ISSUE THREAD

**Issue by Surya059** [stulp/eigenrealtime#1]
Hi,the following code croashes with heap allocation forbidden. Could you please tell how I can calculate inverse without heap allocation?

Eigen::internal::set_is_malloc_allowed(false)
temp5.noalias() = temp2.inverse();
Eigen::internal::set_is_malloc_allowed(false)

**Comment by stulp** [comment]
Perhaps inverse() is implemented in a way that allocates memory (not sure), which would be beyond your control.

See also here some measurements (from 2010...) showing that inverse() indeed allocates memory: http://wiki.ros.org/EigenInRealtime
